### ISSUE TITLE
 Services link in Deploying Challenges tutorial

### ISSUE THREAD

**Issue by izhang05** [CTFd/docs#1]
In the [Deploying Challenges](https://docs.ctfd.io/tutorials/deploying-challenges/#creating-services) section of the tutorial, it says 

> Login as an administrator and navigate to the Admin Panel.
Click on the “Services” link on the top right

However, when I log into demo.ctfd.io as an admin, I do not see the "Services" link after navigating to the Admin Panel.

**Comment by ColdHeat** [comment]
Services aren't available on demo at this time. Not really worth the additional overhead and management especially b/c you can always use your own additional infrastructure. If this changes, documentation will be updated.
